# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 13:47
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today),
            preserve_default=False,
        ),
    ]
